version: "3.8"

services:
  model_server:
    build: ./model_server
    container_name: model_server
    ports:
      - "8000:8000"

  cls_server:
    build: ./cls_server
    container_name: cls_server
    ports:
      - "8001:8001"
    environment:
      - MODEL_SERVER_HOST=model_server
      - MODEL_SERVER_PORT=8000
    depends_on:
      - model_server
